
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: elk
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }

    output {
      stdout { codec => rubydebug }
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
      }
    }

